Repository rails-sqlserver/activerecord-sqlserver-adapter, pull requests merged in 2024-10, with the labels that each got.

#1231 Enable identity insert on view's base table
  .github/workflows/ci.yml
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/database_statements.rb
  test/cases/view_test_sqlserver.rb
Labels: rails-7.2

#1232 Enable identity insert on view's base table
  .github/workflows/ci.yml
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/database_statements.rb
  test/cases/view_test_sqlserver.rb
Labels: rails-7.1

#1233 Coerce test
  test/cases/coerced_tests.rb
Labels: rails-7.1

#1234 Fix update-all for composite key
  lib/arel/visitors/sqlserver.rb
Labels: rails-7.1

#1235 Coerce test
  test/cases/coerced_tests.rb
Labels: rails-7.1

#1236 Release v7.1.8
  CHANGELOG.md
  README.md
  VERSION
Labels: rails-7.1

#1239 Fix for PredicateBuilderTest
  test/cases/coerced_tests.rb
Labels: rails-8.0

#1238 Allow INSERT statements with SELECT notation
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  test/cases/schema_test_sqlserver.rb
Labels: rails-8.0

#1242 Updated sample code for connection configuration
  README.md
Labels: rails-8.0

#1244 Allow INSERT statements with SELECT notation
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  test/cases/schema_test_sqlserver.rb
Labels: rails-7.2

#1245 Allow INSERT statements with SELECT notation
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  test/cases/schema_test_sqlserver.rb
Labels: rails-7.1

#1246 Fix queries with date and date-time placeholder conditions
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/database_statements.rb
  test/cases/adapter_test_sqlserver.rb
Labels: rails-8.0

#1247 Fix queries with date and date-time placeholder conditions
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/database_statements.rb
  test/cases/adapter_test_sqlserver.rb
Labels: rails-7.2

#1251 Fix CI for Rails 8.0.0.rc1
  .devcontainer/Dockerfile
  Dockerfile.ci
  docker-compose.ci.yml
Labels: ci, rails-8.0

#1252 Fix tests for Rails 8.0.0.rc1
  test/cases/coerced_tests.rb
Labels: rails-8.0

#1249 Binary basic columns should be limitable
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  test/cases/schema_dumper_test_sqlserver.rb
  test/schema/sqlserver_specific_schema.rb
Labels: rails-8.0

#1253 Binary basic columns should be limitable
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  test/cases/schema_dumper_test_sqlserver.rb
  test/schema/sqlserver_specific_schema.rb
Labels: rails-7.2
