Repository rails-sqlserver/activerecord-sqlserver-adapter, pull requests merged in 2024-12, with the labels that each got.

#1263 Release v8.0.1
  .github/workflows/ci.yml
  CHANGELOG.md
  VERSION
Labels: rails-8.0

#1264 Release v7.2.3
  CHANGELOG.md
  VERSION
Labels: rails-7.2

#1265 Release v7.1.10
  CHANGELOG.md
  VERSION
Labels: rails-7.1

#1266 Fix CI
  .devcontainer/Dockerfile
  VERSION
  activerecord-sqlserver-adapter.gemspec
Labels: ci, rails-8.1

#1268 Add affected_rows to sql.active_record
  lib/active_record/connection_adapters/sqlserver/database_statements.rb
  test/cases/coerced_tests.rb
Labels: rails-8.1

#1270 Fix parsing of raw table name from SQL with extra parentheses
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  test/cases/schema_test_sqlserver.rb
Labels: rails-7.2

#1271 Fix parsing of raw table name from SQL with extra parentheses
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  test/cases/schema_test_sqlserver.rb
Labels: rails-7.1

#1272 Fix parsing of raw table name from SQL with extra parentheses
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  test/cases/schema_test_sqlserver.rb
Labels: rails-8.0

#1274 Coerce test
  test/cases/coerced_tests.rb
Labels: rails-8.1

#1275 Remove special handling for older TDS connections
  test/cases/column_test_sqlserver.rb
  test/cases/schema_dumper_test_sqlserver.rb
  test/support/connection_reflection.rb
Labels: rails-8.1

#1277 Not compatible with TinyTDS v3+
  CHANGELOG.md
  activerecord-sqlserver-adapter.gemspec
Labels: rails-7.2

#1276 Not compatible with TinyTDS v3+
  CHANGELOG.md
  activerecord-sqlserver-adapter.gemspec
Labels: rails-8.0

#1278 Not compatible with TinyTDS v3+
  CHANGELOG.md
  activerecord-sqlserver-adapter.gemspec
Labels: rails-7.1

#1279 Revert "Not compatible with TinyTDS v3+"
  CHANGELOG.md
  activerecord-sqlserver-adapter.gemspec
Labels: rails-7.1

#1280 Revert "Not compatible with TinyTDS v3+"
  CHANGELOG.md
  activerecord-sqlserver-adapter.gemspec
Labels: rails-7.2

#1281 Revert "Not compatible with TinyTDS v3+"
  CHANGELOG.md
  activerecord-sqlserver-adapter.gemspec
Labels: rails-8.0
