Repository rails-sqlserver/activerecord-sqlserver-adapter, pull requests merged in 2025-03, with the labels that each got.

#1306 Fix affected rows count when lowercase schema reflection enabled
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/database_statements.rb
  test/cases/adapter_test_sqlserver.rb
Labels: bug, rails-8.0

#1308 Fix retrieval of temporary table's column information
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  lib/active_record/connection_adapters/sqlserver/utils.rb
  test/cases/temporary_table_test_sqlserver.rb
Labels: bug, rails-8.1

#1309 Fix retrieval of temporary table's column information
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  lib/active_record/connection_adapters/sqlserver/utils.rb
  test/cases/temporary_table_test_sqlserver.rb
Labels: rails-8.0

#1310 Fix retrieval of temporary table's column information
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  lib/active_record/connection_adapters/sqlserver/utils.rb
  test/cases/temporary_table_test_sqlserver.rb
Labels: rails-7.2

#1311 Coerce tests that use LIMIT in SQL
  test/cases/coerced_tests.rb
Labels: rails-8.1

#1314 Small refactor of Support insert_all and upsert_all using MERGE
  lib/active_record/connection_adapters/sqlserver/database_statements.rb
Labels: rails-8.1

#1312 Support `insert_all` and `upsert_all` using `MERGE`
  CHANGELOG.md
  README.md
  lib/active_record/connection_adapters/sqlserver/database_statements.rb
  lib/active_record/connection_adapters/sqlserver/schema_statements.rb
  lib/active_record/connection_adapters/sqlserver_adapter.rb
  test/cases/adapter_test_sqlserver.rb
  test/cases/coerced_tests.rb
  test/cases/schema_test_sqlserver.rb
Labels: feature, rails-8.1

#1313 Correctly retrieve the SQL Server database version
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver_adapter.rb
  test/cases/helper_sqlserver.rb
Labels: rails-8.1

#1317 Reverse order of values when upserting
  CHANGELOG.md
  lib/active_record/connection_adapters/sqlserver/database_statements.rb
Labels: rails-8.1
